# Site settings
title: Artificial Intelligence and Statistics Conference
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS 2026 conference.
baseurl: "/aistats2026/" # the subpath of your site, e.g. /blog/

repository: aistats/aistats2026

# If you want to create a twitter account for your conference include
# twitter name here
twitter_username: 

github_username:  aistats

author:
  name: AISTATS
  # YOu might want to create an email for handling conference queries, e.g. aistats20XX@gmail.com. If you do, you can enter it here.
  email: aistats2026@gmail.com
comments: false

# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# change encoding for the generated output files to utf-8
encoding: utf-8
remote_theme: aistats/jekyll-theme
style: aistats

ghub:
  edit: true
  repository: aistats2026


# Place a banner image in assets/images and give its name here.
banner: tangier.jpg 
banner_title: Artificial Intelligence and Statistics 2026

conference:
  full_name: Artificial Intelligence and Statistics
  short_name: AISTATS
  name: Artificial Intelligence and Statistics
  # set to True if the programme is draft only.
  draft: true
  # set to True to hide tentative speakers
  hide_tentative: true 
  # Place an image of venue in assets/images and give its name here
  image: conference-venue.png
  proceedings:
    # When proceedings are published add url here.
    url:      
    show: false
  # Give details of the room in the venue here.  
  room:
  # Set the name of the venue (e.g. Caribe Hilton Hotel)  
  venue:
  # Give the url of the venue here.  
  venue_url:
  # Give the conference location in the form City, Country here.
  location: Morocco
  year: 2026
  # Give the instance of the conference here (e.g. 24th)
  instance: 29th
  # Styling for AISTATS is "International Conference"  
  styling: International Conference on
  # Give the individual days that the conference will be held on here.
  dates:
  - 2025-05-02
  - 2025-05-03
  - 2025-05-04
  - 2025-05-05  
  # Give the submission site details here.
  submission:
    # Whether to show the submission site.
    show: 
    # The URL of the submission site.
    url: 
    # The name of the submission site (e.g. Microsoft CMT Website)
    name: 
  deadlines:
    # Fill in the key dates as below.
    - name: Submission server open
      type: submission
      date: 
    - name: Paper submission deadline
      type: submission
      time: 
    - name: Author response period starts
      date: 
    - name: Author response period ends
      time:
    - name: Paper decision notifications
      date: 
      type: decision
    - name: Deadline for camera-ready papers
      time: 
    - name: Registration deadline
      date:
  # List program chairs here.      
  chairs:
  - type: General Chairs
    people:
    - family: Li
      given: Yingzhen
      url: http://yingzhenli.net/
      institute: Imperial College London
    - family: Khan
      given: Emtiyaz
      url: https://emtiyaz.github.io/
      institute: RIKEN
  - type: Program Chairs
    people:
    - family: Solin
      given: Arno
      url: https://arno.solin.fi
      institute: Aalto University
    - family: Ramdas
      given: Aaditya
      url: https://www.stat.cmu.edu/~aramdas
      institute: Carnegie Mellon University
  # You might want Workflow Chair(s) to assist with your submission system and the review process.     
  - type: Workflow Chairs
    people:
    - family: Choe 
      given: Yo Joong
      url: https://yjchoe.github.io/
      institute: INSEAD
    - family: Verma 
      given: Prakhar
      url: https://prakharverma.github.io/
      institute: Aalto University
  - type: Workshop Chairs
    people:
    - family: Vernade
      given: Claire
      url: https://www.cvernade.com/
      institute: University of Tübingen
    - family: Berthet
      given: Quentin
      url: https://q-berthet.github.io/
      institute: Google DeepMind
  # D&I Chairs look after initiatives to ensure an inclusive conference      
  - type: Inclusivity Chair
    people:
    - family: Agrawal
      given: Shubhada
      url: https://sites.google.com/view/shubhada-agrawal/home
      institute: Indian Institute of Science, Bangalore      
  # Journal-to-Conference Chairs      
  - type: Journal-to-Conference Chair
    people:
    - family: Daudel
      given: Kamélia 
      url: https://kdaudel.github.io/
      institute: ESSEC Business School
    - family: Alquier
      given: Pierre
      url: https://pierrealquier.github.io/
      institute: ESSEC Business School
  # Sponsorship
  - type: Sponsorship Chairs
    people:
    - family: Fortuin
      given: Vincent
      url: https://fortuin.github.io/
      institute: Helmholtz AI & TU Munich
    - family: Kristiadi
      given: Agustinus
      url: https://agustinus.kristia.de/
      institute: Western University & Vector Institute
  # Local Chairs
  - type: Local Chairs
    people:
    - family: BEN TAIEB
      given: Souhaib
      url: https://souhaib-bentaieb.com/
      institute: 
    - family: Harrasse
      given: Abir
      url: https://abirharrasse.github.io/
      institute: Martian Learning Inc.
    - family: Lahlou
      given: Salem
      url: https://lahlou.org/
      institute: MBZUAI
  # Publication Chair
  - type: Publication Chair
    people:
    - family: Trapp
      given: Martin
      url: https://trappmartin.github.io/
      institute: KTH Royal Institute of Technology
